-- This file should undo anything in `up.sql`
DROP FUNCTION IF EXISTS GETVOTES_BYPARLIAMENT;
DROP FUNCTION IF EXISTS GETVOTINGS_BYPARLIAMENT;
DROP FUNCTION IF EXISTS GETVOTINGS;
DROP FUNCTION IF EXISTS GETAGENDAS;
DROP FUNCTION IF EXISTS GETSESSIONS;